# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 11, 31, 56, 488193, tzinfo=utc)),
        ),
    ]
